# Generated by Django 5.1.1 on 2025-07-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Необязательно', upload_to='images/avatars/', verbose_name='Изображение'),
        ),
    ]
