# Generated by Django 5.1.1 on 2025-07-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1, max_length=150, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
